### ISSUE TITLE
Use spot instances

### ISSUE THREAD

**Issue by jairideout** [caporaso-lab-graveyard/clout#17]
This could potentially save us money and is a perfect use case (if the test suites get killed, who cares...).

**Comment by jairideout** [comment]
Looked into this a bit further. StarCluster doesn't create master nodes that are spot instances for stability reasons (only worker nodes can be spot instances).

Clout currently creates a single master node to run the tests on, so if we wanted to use spot instances, we'd need Clout to start a master node (a t1.micro or something) with spot worker nodes to run the tests on. The advantage would be that we could run multiple tests suites at the same time on different spot worker nodes.

@gregcaporaso, do you have any thoughts on this?

**Comment by gregcaporaso** [comment]
> we'd need Clout to start a master node (a t1.micro or something) with spot worker nodes to run the tests on. The advantage would be that we could run multiple tests suites at the same time on different spot worker nodes.

I think that could be a cool solution. How much work would it be?

**Comment by jairideout** [comment]
It depends on how fancy we'd want to get with executing test suites on multiple worker nodes at once. I think the first step would be to get it working with a single `t1.micro` and a single spot worker node, which I don't think would be too much work (i.e. a few hours, including testing, which takes up most of the time). We'd end up saving a lot of money over time since the `t1.micro` is basically free (2 cents an hour) and the spot instance will be much cheaper than the current on-demand price that we're paying.

**Comment by gregcaporaso** [comment]
Cool, go for it.
